teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.3
  scale_linear_turbo: 0.5
  axis_angular: 0
  scale_angular: 3.2
  enable_button: 0
  enable_turbo_button: 1
joy_node: 
  deadzone: 0.05
  autorepeat_rate: 20
