teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.2
  scale_linear_turbo: 0.5
  axis_angular: 0
  scale_angular: 1.2
  enable_button: 0
  enable_turbo_button: 2
joy_node: 
  deadzone: 0.1
  autorepeat_rate: 20
